version: 2
updates:
    -   package-ecosystem: "npm"
        directory: "/"
        schedule:
            interval: "daily"
        ignore:
            -   dependency-name: "sass"
            -   dependency-name: "bootstrap"
            -   dependency-name: "bootswatch"
