# This workflow will do a clean install of Node dependencies, ensures that a build runs successfully, and triggers deployment via a webhook.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
      env:
        NODE_ENV: "production"
        API_GRAPHQL_URL: ${{ secrets.API_GRAPHQL_URL }}
    #- run: npm test
    - name: Workflow Webhook Action
      uses: distributhor/workflow-webhook@v1.0.8
      with:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
        webhook_type: "json"
        silent: true
